In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("drive/MyDrive/Colab Notebooks/Veriler/veriler.csv")

In [3]:
df.head()

ulke  boy  kilo  yas cinsiyet
0   tr  130    30   10        e
1   tr  125    36   11        e
2   tr  135    34   10        k
3   tr  133    30    9        k
4   tr  129    38   12        e

In [4]:
ulke = df.iloc[:,0:1].values

In [5]:
from sklearn import preprocessing

In [6]:
le = preprocessing.LabelEncoder()

In [7]:
# LabelEncoder kullanarak ülke sütununu kodlar
ulke[:,0] =le.fit_transform(df.iloc[:,0])

In [8]:
ulke

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=object)

In [9]:
# OneHotEncoder kullanarak ülke sütununu one-hot encode eder
ohe = preprocessing.OneHotEncoder()
ulke = ohe.fit_transform(ulke).toarray()

In [10]:
ulke

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [11]:
cinsiyet = df.iloc[:,-1:].values

In [12]:
cinsiyet

array([['e'],
       ['e'],
       ['k'],
       ['k'],
       ['e'],
       ['e'],
       ['e'],
       ['e'],
       ['k'],
       ['e'],
       ['k'],
       ['k'],
       ['k'],
       ['k'],
       ['k'],
       ['e'],
       ['e'],
       ['e'],
       ['e'],
       ['k'],
       ['k'],
       ['k']], dtype=object)

In [13]:
cinsiyet[:,-1] = le.fit_transform(df.iloc[:,-1])

In [14]:
cinsiyet = ohe.fit_transform(cinsiyet).toarray()

In [15]:
cinsiyet

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [16]:
sonuc = pd.DataFrame(data=ulke, index=range(22), columns=["fr","tr","us"])

In [17]:
sonuc

fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0

In [18]:
sonuc2 = pd.DataFrame(data=cinsiyet[:,:1], index = range(22), columns= ["cinsiyet"])

In [19]:
sonuc2

cinsiyet
0        1.0
1        1.0
2        0.0
3        0.0
4        1.0
5        1.0
6        1.0
7        1.0
8        0.0
9        1.0
10       0.0
11       0.0
12       0.0
13       0.0
14       0.0
15       1.0
16       1.0
17       1.0
18       1.0
19       0.0
20       0.0
21       0.0

In [20]:
sonuc3 = pd.DataFrame(data=df, index = range(22), columns = ['boy','kilo','yas'])

In [21]:
sonuc3

boy  kilo  yas
0   130    30   10
1   125    36   11
2   135    34   10
3   133    30    9
4   129    38   12
5   180    90   30
6   190    80   25
7   175    90   35
8   177    60   22
9   185   105   33
10  165    55   27
11  155    50   44
12  160    58   39
13  162    59   41
14  167    62   55
15  174    70   47
16  193    90   23
17  187    80   27
18  183    88   28
19  159    40   29
20  164    66   32
21  166    56   42

In [22]:
sonuc_df = pd.concat([sonuc,sonuc3],axis=1)

In [23]:
sonuc_df2 = pd.concat([sonuc_df,sonuc2],axis=1)

In [24]:
sonuc_df

fr   tr   us  boy  kilo  yas
0   0.0  1.0  0.0  130    30   10
1   0.0  1.0  0.0  125    36   11
2   0.0  1.0  0.0  135    34   10
3   0.0  1.0  0.0  133    30    9
4   0.0  1.0  0.0  129    38   12
5   0.0  1.0  0.0  180    90   30
6   0.0  1.0  0.0  190    80   25
7   0.0  1.0  0.0  175    90   35
8   0.0  1.0  0.0  177    60   22
9   0.0  0.0  1.0  185   105   33
10  0.0  0.0  1.0  165    55   27
11  0.0  0.0  1.0  155    50   44
12  0.0  0.0  1.0  160    58   39
13  0.0  0.0  1.0  162    59   41
14  0.0  0.0  1.0  167    62   55
15  1.0  0.0  0.0  174    70   47
16  1.0  0.0  0.0  193    90   23
17  1.0  0.0  0.0  187    80   27
18  1.0  0.0  0.0  183    88   28
19  1.0  0.0  0.0  159    40   29
20  1.0  0.0  0.0  164    66   32
21  1.0  0.0  0.0  166    56   42

In [25]:
sonuc_df2

fr   tr   us  boy  kilo  yas  cinsiyet
0   0.0  1.0  0.0  130    30   10       1.0
1   0.0  1.0  0.0  125    36   11       1.0
2   0.0  1.0  0.0  135    34   10       0.0
3   0.0  1.0  0.0  133    30    9       0.0
4   0.0  1.0  0.0  129    38   12       1.0
5   0.0  1.0  0.0  180    90   30       1.0
6   0.0  1.0  0.0  190    80   25       1.0
7   0.0  1.0  0.0  175    90   35       1.0
8   0.0  1.0  0.0  177    60   22       0.0
9   0.0  0.0  1.0  185   105   33       1.0
10  0.0  0.0  1.0  165    55   27       0.0
11  0.0  0.0  1.0  155    50   44       0.0
12  0.0  0.0  1.0  160    58   39       0.0
13  0.0  0.0  1.0  162    59   41       0.0
14  0.0  0.0  1.0  167    62   55       0.0
15  1.0  0.0  0.0  174    70   47       1.0
16  1.0  0.0  0.0  193    90   23       1.0
17  1.0  0.0  0.0  187    80   27       1.0
18  1.0  0.0  0.0  183    88   28       1.0
19  1.0  0.0  0.0  159    40   29       0.0
20  1.0  0.0  0.0  164    66   32       0.0
21  1.0  0.0  0.0  166    56   42       0.0

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
# Eğitim ve test kümelerine veri bölme işlemi yapar
x_train, x_test,y_train,y_test = train_test_split(sonuc_df,sonuc2,test_size=0.33, random_state=0)

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
regressor = LinearRegression()

In [30]:
regressor.fit(x_train,y_train)

LinearRegression()

In [31]:
# Test kümesi üzerinde tahmin yapın
y_pred = regressor.predict(x_test)

In [32]:
# Eğitim sonucu ile test sonucunu karşılaştırın
y_pred,y_test

(array([[ 0.98720204],
        [-0.12036863],
        [ 0.05009703],
        [ 0.07137418],
        [ 0.72473935],
        [ 0.64615044],
        [-0.03567453],
        [ 0.32612171]]),
     cinsiyet
 20       0.0
 10       0.0
 14       0.0
 13       0.0
 1        1.0
 21       0.0
 11       0.0
 19       0.0)

In [33]:
sonuc_df2

fr   tr   us  boy  kilo  yas  cinsiyet
0   0.0  1.0  0.0  130    30   10       1.0
1   0.0  1.0  0.0  125    36   11       1.0
2   0.0  1.0  0.0  135    34   10       0.0
3   0.0  1.0  0.0  133    30    9       0.0
4   0.0  1.0  0.0  129    38   12       1.0
5   0.0  1.0  0.0  180    90   30       1.0
6   0.0  1.0  0.0  190    80   25       1.0
7   0.0  1.0  0.0  175    90   35       1.0
8   0.0  1.0  0.0  177    60   22       0.0
9   0.0  0.0  1.0  185   105   33       1.0
10  0.0  0.0  1.0  165    55   27       0.0
11  0.0  0.0  1.0  155    50   44       0.0
12  0.0  0.0  1.0  160    58   39       0.0
13  0.0  0.0  1.0  162    59   41       0.0
14  0.0  0.0  1.0  167    62   55       0.0
15  1.0  0.0  0.0  174    70   47       1.0
16  1.0  0.0  0.0  193    90   23       1.0
17  1.0  0.0  0.0  187    80   27       1.0
18  1.0  0.0  0.0  183    88   28       1.0
19  1.0  0.0  0.0  159    40   29       0.0
20  1.0  0.0  0.0  164    66   32       0.0
21  1.0  0.0  0.0  166    56   42       0.0

In [34]:
boy = sonuc_df2.iloc[:,3:4].values

In [35]:
boy

array([[130],
       [125],
       [135],
       [133],
       [129],
       [180],
       [190],
       [175],
       [177],
       [185],
       [165],
       [155],
       [160],
       [162],
       [167],
       [174],
       [193],
       [187],
       [183],
       [159],
       [164],
       [166]])

In [36]:
# Sol ve sağ veri kümelerini ayırır
sol = sonuc_df2.iloc[:,:3]
sag = sonuc_df2.iloc[:,4:]

In [37]:
sag

kilo  yas  cinsiyet
0     30   10       1.0
1     36   11       1.0
2     34   10       0.0
3     30    9       0.0
4     38   12       1.0
5     90   30       1.0
6     80   25       1.0
7     90   35       1.0
8     60   22       0.0
9    105   33       1.0
10    55   27       0.0
11    50   44       0.0
12    58   39       0.0
13    59   41       0.0
14    62   55       0.0
15    70   47       1.0
16    90   23       1.0
17    80   27       1.0
18    88   28       1.0
19    40   29       0.0
20    66   32       0.0
21    56   42       0.0

In [38]:
sol

fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0

In [39]:
veri = pd.concat([sol,sag],axis=1)

In [40]:
veri

fr   tr   us  kilo  yas  cinsiyet
0   0.0  1.0  0.0    30   10       1.0
1   0.0  1.0  0.0    36   11       1.0
2   0.0  1.0  0.0    34   10       0.0
3   0.0  1.0  0.0    30    9       0.0
4   0.0  1.0  0.0    38   12       1.0
5   0.0  1.0  0.0    90   30       1.0
6   0.0  1.0  0.0    80   25       1.0
7   0.0  1.0  0.0    90   35       1.0
8   0.0  1.0  0.0    60   22       0.0
9   0.0  0.0  1.0   105   33       1.0
10  0.0  0.0  1.0    55   27       0.0
11  0.0  0.0  1.0    50   44       0.0
12  0.0  0.0  1.0    58   39       0.0
13  0.0  0.0  1.0    59   41       0.0
14  0.0  0.0  1.0    62   55       0.0
15  1.0  0.0  0.0    70   47       1.0
16  1.0  0.0  0.0    90   23       1.0
17  1.0  0.0  0.0    80   27       1.0
18  1.0  0.0  0.0    88   28       1.0
19  1.0  0.0  0.0    40   29       0.0
20  1.0  0.0  0.0    66   32       0.0
21  1.0  0.0  0.0    56   42       0.0

In [41]:
# Veriyi eğitim ve test kümelerine bölün
x_train, x_test,y_train,y_test = train_test_split(veri,boy,test_size=0.33, random_state=0)

In [42]:
x_train

fr   tr   us  kilo  yas  cinsiyet
8   0.0  1.0  0.0    60   22       0.0
6   0.0  1.0  0.0    80   25       1.0
16  1.0  0.0  0.0    90   23       1.0
4   0.0  1.0  0.0    38   12       1.0
2   0.0  1.0  0.0    34   10       0.0
5   0.0  1.0  0.0    90   30       1.0
17  1.0  0.0  0.0    80   27       1.0
9   0.0  0.0  1.0   105   33       1.0
7   0.0  1.0  0.0    90   35       1.0
18  1.0  0.0  0.0    88   28       1.0
3   0.0  1.0  0.0    30    9       0.0
0   0.0  1.0  0.0    30   10       1.0
15  1.0  0.0  0.0    70   47       1.0
12  0.0  0.0  1.0    58   39       0.0

In [43]:
# Lineer regresyon modeli oluşturun ve eğitin
r2 = LinearRegression()
r2.fit(x_train, y_train)

LinearRegression()

In [44]:
# Test kümesi üzerinde tahmin yapın
y_pred = r2.predict(x_test)

In [45]:
y_pred # Tahmin sonuçları

array([[182.26638686],
       [152.87161474],
       [162.79386375],
       [158.30668577],
       [130.82888952],
       [173.96138408],
       [150.12782663],
       [157.26898922]])

In [46]:
y_test # Gerçek sonuçlar

array([[164],
       [165],
       [167],
       [162],
       [125],
       [166],
       [155],
       [159]])

**Modeldeki başarısını arttırmak için backward elimination uygulandı**

In [47]:
import statsmodels.api as sm

In [48]:
X = np.append(arr = np.ones((22,1)).astype(int),values=veri, axis=1)

In [49]:
X

array([[  1.,   0.,   1.,   0.,  30.,  10.,   1.],
       [  1.,   0.,   1.,   0.,  36.,  11.,   1.],
       [  1.,   0.,   1.,   0.,  34.,  10.,   0.],
       [  1.,   0.,   1.,   0.,  30.,   9.,   0.],
       [  1.,   0.,   1.,   0.,  38.,  12.,   1.],
       [  1.,   0.,   1.,   0.,  90.,  30.,   1.],
       [  1.,   0.,   1.,   0.,  80.,  25.,   1.],
       [  1.,   0.,   1.,   0.,  90.,  35.,   1.],
       [  1.,   0.,   1.,   0.,  60.,  22.,   0.],
       [  1.,   0.,   0.,   1., 105.,  33.,   1.],
       [  1.,   0.,   0.,   1.,  55.,  27.,   0.],
       [  1.,   0.,   0.,   1.,  50.,  44.,   0.],
       [  1.,   0.,   0.,   1.,  58.,  39.,   0.],
       [  1.,   0.,   0.,   1.,  59.,  41.,   0.],
       [  1.,   0.,   0.,   1.,  62.,  55.,   0.],
       [  1.,   1.,   0.,   0.,  70.,  47.,   1.],
       [  1.,   1.,   0.,   0.,  90.,  23.,   1.],
       [  1.,   1.,   0.,   0.,  80.,  27.,   1.],
       [  1.,   1.,   0.,   0.,  88.,  28.,   1.],
       [  1.,   1.,   0.,   0.,

In [50]:
X_l = veri.iloc[:,[0,1,2,3,4,5]].values
X_l = np.array(X_l, dtype=float)
model = sm.OLS(boy, X_l).fit()

In [51]:
X_l

array([[  0.,   1.,   0.,  30.,  10.,   1.],
       [  0.,   1.,   0.,  36.,  11.,   1.],
       [  0.,   1.,   0.,  34.,  10.,   0.],
       [  0.,   1.,   0.,  30.,   9.,   0.],
       [  0.,   1.,   0.,  38.,  12.,   1.],
       [  0.,   1.,   0.,  90.,  30.,   1.],
       [  0.,   1.,   0.,  80.,  25.,   1.],
       [  0.,   1.,   0.,  90.,  35.,   1.],
       [  0.,   1.,   0.,  60.,  22.,   0.],
       [  0.,   0.,   1., 105.,  33.,   1.],
       [  0.,   0.,   1.,  55.,  27.,   0.],
       [  0.,   0.,   1.,  50.,  44.,   0.],
       [  0.,   0.,   1.,  58.,  39.,   0.],
       [  0.,   0.,   1.,  59.,  41.,   0.],
       [  0.,   0.,   1.,  62.,  55.,   0.],
       [  1.,   0.,   0.,  70.,  47.,   1.],
       [  1.,   0.,   0.,  90.,  23.,   1.],
       [  1.,   0.,   0.,  80.,  27.,   1.],
       [  1.,   0.,   0.,  88.,  28.,   1.],
       [  1.,   0.,   0.,  40.,  29.,   0.],
       [  1.,   0.,   0.,  66.,  32.,   0.],
       [  1.,   0.,   0.,  56.,  42.,   0.]])

In [52]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.885
Model:                            OLS   Adj. R-squared:                  0.849
Method:                 Least Squares   F-statistic:                     24.69
Date:                Sun, 31 Mar 2024   Prob (F-statistic):           5.41e-07
Time:                        12:37:52   Log-Likelihood:                -73.950
No. Observations:                  22   AIC:                             159.9
Df Residuals:                      16   BIC:                             166.4
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           114.0688      8.145     14.005      0.000      96.802     131.335
x2           108.3030      5.736     18.880      0.000      96.143     120.463
x3           104.4714      9.195     11.361      0.000      84.978     123.964
x4             0.9211      0.119      7.737      0.000       0.669       1.174
x5             0.0814      0.221      0.369      0.717      -0.386       0.549
x6           -10.5980      5.052     -2.098      0.052     -21.308       0.112
==============================================================================
Omnibus:                        1.031   Durbin-Watson:                   2.759
Prob(Omnibus):                  0.597   Jarque-Bera (JB):                0.624
Skew:                           0.407   Prob(JB):                        0.732
Kurtosis:                       2.863   Cond. No.                         524.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [53]:
X_l = veri.iloc[:,[0,1,2,3,5]].values
X_l = np.array(X_l, dtype=float)
model = sm.OLS(boy, X_l).fit()

In [54]:
model.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.884
Model:                            OLS   Adj. R-squared:                  0.857
Method:                 Least Squares   F-statistic:                     32.47
Date:                Sun, 31 Mar 2024   Prob (F-statistic):           9.32e-08
Time:                        12:37:52   Log-Likelihood:                -74.043
No. Observations:                  22   AIC:                             158.1
Df Residuals:                      17   BIC:                             163.5
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           115.6583      6.734     17.175      0.000     101.451     129.866
x2           109.0786      5.200     20.978      0.000      98.108     120.049
x3           106.5445      7.090     15.026      0.000      91.585     121.504
x4             0.9405      0.104      9.029      0.000       0.721       1.160
x5           -11.1093      4.733     -2.347      0.031     -21.096      -1.123
==============================================================================
Omnibus:                        0.871   Durbin-Watson:                   2.719
Prob(Omnibus):                  0.647   Jarque-Bera (JB):                0.459
Skew:                           0.351   Prob(JB):                        0.795
Kurtosis:                       2.910   Cond. No.                         397.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [55]:
X_l = veri.iloc[:,[0,1,2,3]].values
X_l = np.array(X_l, dtype=float)
model = sm.OLS(boy, X_l).fit()

In [56]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.847
Model:                            OLS   Adj. R-squared:                  0.821
Method:                 Least Squares   F-statistic:                     33.16
Date:                Sun, 31 Mar 2024   Prob (F-statistic):           1.52e-07
Time:                        12:37:52   Log-Likelihood:                -77.131
No. Observations:                  22   AIC:                             162.3
Df Residuals:                      18   BIC:                             166.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           119.8136      7.265     16.491      0.000     104.550     135.077
x2           109.8084      5.804     18.919      0.000      97.615     122.002
x3           114.4212      6.984     16.382      0.000      99.747     129.095
x4             0.7904      0.092      8.595      0.000       0.597       0.984
==============================================================================
Omnibus:                        2.925   Durbin-Watson:                   2.855
Prob(Omnibus):                  0.232   Jarque-Bera (JB):                1.499
Skew:                           0.605   Prob(JB):                        0.473
Kurtosis:                       3.416   Cond. No.                         369.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""